project_name: volt

before:
  hooks:
    - go mod tidy
    - go test ./...

builds:
  - id: volt
    binary: volt
    main: ./cmd/volt/main.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    flags:
      - -trimpath
    ldflags:
      - -s -w

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'

#brews:
#  - name: volt
#    repository:
#      owner: owenHochwald
#      name: homebrew-volt
#    homepage: https://github.com/owenHochwald/Volt
#    description: "High-performance, concurrent, terminal-based HTTP client"
#    license: "MPL 2.0"

release:
  draft: true